# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: x is for
email: hi@xisfor.tech
description: > # this means to ignore newlines until "baseurl:"
  Web app development that creates a great experience for everyone. Based in Birmingham, UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xisfor.tech" # the base hostname & protocol for your site
twitter_username: xisfortech
github_username:  xisfor
phone_number: "07870332981"

# Build settings
markdown: kramdown
